"""
Content improvement engine.
Uses Claude API to generate E-E-A-T-optimized improvements and SEO suggestions.
"""

import json
import logging
import os
from dataclasses import dataclass, field

import anthropic

from analyzer import EEATReport
from scraper import BlogContent

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """\
You are an expert SEO content strategist specializing in Google's E-E-A-T \
(Experience, Expertise, Authoritativeness, Trustworthiness) framework. Your \
goal is to improve blog content so it ranks better while staying authentic \
and human.

Core principles:
- Authenticity over polish: real-sounding content beats perfectly structured AI text.
- Specific over generic: replace vague claims with concrete details, numbers, names, dates.
- Mark where ONLY a human can contribute: use [MANUAL INPUT NEEDED: description] markers.
- Provide OPTIONS, not single rewrites — give 2-3 alternatives when rewriting sections.
- Cite recent sources (2023-2025) when recommending data points or statistics.
- Identify exactly WHERE human expertise adds the most value.
- Vary sentence structure and length — mix short punchy sentences with longer ones.
- Use natural transitions, not mechanical ones like "Furthermore" or "Additionally".

Output format: Always respond with valid JSON matching the requested schema.\
"""


@dataclass
class ImprovementResult:
    """All improvements generated by the Claude API."""
    improved_markdown: str = ""
    experience_suggestions: list[dict] = field(default_factory=list)
    expertise_questions: list[str] = field(default_factory=list)
    data_opportunities: list[dict] = field(default_factory=list)
    citation_spots: list[dict] = field(default_factory=list)
    faq_questions: list[str] = field(default_factory=list)
    trust_recommendations: list[str] = field(default_factory=list)
    ai_phrase_rewrites: list[dict] = field(default_factory=list)
    quick_answer: str = ""
    schema_suggestions: dict = field(default_factory=dict)
    heading_rewrites: list[dict] = field(default_factory=list)
    related_questions: list[str] = field(default_factory=list)


def _get_client(api_key: str | None = None) -> anthropic.Anthropic:
    """Create an Anthropic client."""
    key = api_key or os.environ.get("ANTHROPIC_API_KEY")
    if not key:
        raise RuntimeError(
            "Anthropic API key required. Pass --api-key or set ANTHROPIC_API_KEY env var."
        )
    return anthropic.Anthropic(api_key=key)


def _call_claude(
    client: anthropic.Anthropic,
    user_prompt: str,
    max_tokens: int = 4096,
) -> str:
    """Make a single Claude API call and return the text response."""
    message = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=max_tokens,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": user_prompt}],
    )
    return message.content[0].text


def _parse_json_response(text: str) -> dict:
    """Extract and parse JSON from Claude's response, handling markdown fences."""
    cleaned = text.strip()
    # Strip markdown code fences if present
    if cleaned.startswith("```"):
        first_newline = cleaned.index("\n")
        last_fence = cleaned.rfind("```")
        if last_fence > first_newline:
            cleaned = cleaned[first_newline + 1:last_fence].strip()

    return json.loads(cleaned)


def generate_improvements(
    content: BlogContent,
    report: EEATReport,
    api_key: str | None = None,
    preserve_style: bool = False,
    verbose: bool = False,
) -> ImprovementResult:
    """
    Generate all content improvements via Claude API.

    Breaks the work into focused API calls to stay within token limits
    and produce higher-quality results.
    """
    client = _get_client(api_key)
    result = ImprovementResult()

    # Truncate body text for prompts if very long
    body_for_prompt = content.body_text[:6000]
    headings_text = "\n".join(
        f"  {h['level']}: {h['text']}" for h in content.headings
    )
    gaps_text = "\n".join(f"  - {g}" for g in report.missing_elements)
    ai_phrases_text = ", ".join(report.ai_phrases_found) if report.ai_phrases_found else "None found"

    style_instruction = ""
    if preserve_style:
        style_instruction = (
            "\nIMPORTANT: Carefully match the original author's writing style, "
            "tone, and voice. Preserve their personality and characteristic patterns."
        )

    # --- Call 1: Experience suggestions & expertise questions ---
    if verbose:
        logger.info("Generating experience & expertise suggestions...")

    prompt_1 = f"""\
Analyze this blog post and provide experience/expertise improvement suggestions.

TITLE: {content.title}
CURRENT HEADINGS:
{headings_text}

IDENTIFIED GAPS:
{gaps_text}

AI-GENERIC PHRASES FOUND: {ai_phrases_text}

CONTENT (first 6000 chars):
{body_for_prompt}
{style_instruction}

Respond with JSON matching this exact schema:
{{
  "experience_suggestions": [
    {{
      "location": "description of where in the article",
      "suggestion": "what personal experience to add",
      "placeholder": "[MANUAL INPUT NEEDED: ...]"
    }}
  ],
  "expertise_questions": [
    "question the author should answer to demonstrate expertise"
  ],
  "data_opportunities": [
    {{
      "location": "where to add data",
      "suggestion": "what kind of statistic or data point to include",
      "search_tip": "where to find this data (specific source)"
    }}
  ],
  "citation_spots": [
    {{
      "location": "where to add citation",
      "topic": "what to cite",
      "suggested_source_type": "type of source (study, report, expert quote, etc.)"
    }}
  ]
}}

Provide 3-5 items per category. Be specific — reference actual sections of the content.\
"""

    try:
        resp = _call_claude(client, prompt_1, max_tokens=3000)
        data = _parse_json_response(resp)
        result.experience_suggestions = data.get("experience_suggestions", [])
        result.expertise_questions = data.get("expertise_questions", [])
        result.data_opportunities = data.get("data_opportunities", [])
        result.citation_spots = data.get("citation_spots", [])
    except (json.JSONDecodeError, anthropic.APIError) as e:
        logger.error("Call 1 failed: %s", e)

    # --- Call 2: FAQ, trust signals, related questions ---
    if verbose:
        logger.info("Generating FAQ & trust signal suggestions...")

    prompt_2 = f"""\
Based on this blog post, generate FAQ questions, trust recommendations, and \
related questions for AI Overview optimization.

TITLE: {content.title}
TOPIC SUMMARY (first 2000 chars):
{body_for_prompt[:2000]}

AUTHOR: {content.author or 'Not specified'}
PUBLISH DATE: {content.publish_date or 'Not specified'}

Respond with JSON matching this exact schema:
{{
  "faq_questions": [
    "question that would make a good FAQ entry for this topic"
  ],
  "trust_recommendations": [
    "specific trust signal to add (be concrete, not generic)"
  ],
  "related_questions": [
    "related question people also ask about this topic"
  ],
  "quick_answer": "A 2-3 sentence TL;DR summary of the post's main point, written in direct factual style suitable for a featured snippet"
}}

Provide 5-8 FAQ questions, 4-6 trust recommendations, 5-8 related questions.\
"""

    try:
        resp = _call_claude(client, prompt_2, max_tokens=2500)
        data = _parse_json_response(resp)
        result.faq_questions = data.get("faq_questions", [])
        result.trust_recommendations = data.get("trust_recommendations", [])
        result.related_questions = data.get("related_questions", [])
        result.quick_answer = data.get("quick_answer", "")
    except (json.JSONDecodeError, anthropic.APIError) as e:
        logger.error("Call 2 failed: %s", e)

    # --- Call 3: AI phrase rewrites & heading optimization ---
    if verbose:
        logger.info("Generating phrase rewrites & heading improvements...")

    prompt_3 = f"""\
Rewrite generic AI-sounding phrases and optimize headings for this blog post.

TITLE: {content.title}
CURRENT HEADINGS:
{headings_text}

AI-GENERIC PHRASES FOUND: {ai_phrases_text}

CONTENT (first 4000 chars):
{body_for_prompt[:4000]}
{style_instruction}

Respond with JSON matching this exact schema:
{{
  "ai_phrase_rewrites": [
    {{
      "original": "the generic phrase",
      "options": [
        "rewrite option 1 (more specific and natural)",
        "rewrite option 2 (different angle)"
      ],
      "why": "brief reason this sounds generic"
    }}
  ],
  "heading_rewrites": [
    {{
      "original": "Current Heading Text",
      "rewrite": "What Is the Question-Format Heading?",
      "rationale": "why this format is better for search"
    }}
  ]
}}

For ai_phrase_rewrites: cover all flagged phrases plus any others you notice.
For heading_rewrites: convert appropriate headings to natural question format. Not every heading needs to be a question — only where it makes sense.\
"""

    try:
        resp = _call_claude(client, prompt_3, max_tokens=2500)
        data = _parse_json_response(resp)
        result.ai_phrase_rewrites = data.get("ai_phrase_rewrites", [])
        result.heading_rewrites = data.get("heading_rewrites", [])
    except (json.JSONDecodeError, anthropic.APIError) as e:
        logger.error("Call 3 failed: %s", e)

    # --- Call 4: Generate the full improved markdown ---
    if verbose:
        logger.info("Generating improved content markdown...")

    prompt_4 = f"""\
Rewrite and improve this blog post following E-E-A-T principles. \
Produce a complete improved markdown version.

ORIGINAL TITLE: {content.title}
ORIGINAL CONTENT:
{content.body_text[:8000]}

IDENTIFIED GAPS:
{gaps_text}

QUICK ANSWER TO ADD AT TOP:
{result.quick_answer}

FAQ QUESTIONS TO ADD:
{json.dumps(result.faq_questions[:6], indent=2)}
{style_instruction}

Rules for the improved version:
1. Start with a "Quick Answer" / TL;DR section right after the title.
2. Use [MANUAL INPUT NEEDED: description] markers (at least 5) where only a human \
can add value — personal stories, specific results, proprietary data.
3. Add <!-- SUGGESTION: text --> HTML comments for recommended additions.
4. Convert appropriate headings to question format.
5. Add an FAQ section at the end with the provided questions and brief answers.
6. Vary sentence length. Mix 5-word punches with 20-word explanations.
7. Use natural transitions, not "Furthermore" / "Additionally" / "Moreover".
8. Include placeholder citations like [CITE: description of needed source].
9. Maintain the original post's core message and structure.
10. Do NOT use generic phrases like "In today's digital world" or "game-changer".

Output ONLY the improved markdown content. No JSON wrapper — just the markdown.\
"""

    try:
        resp = _call_claude(client, prompt_4, max_tokens=6000)
        result.improved_markdown = resp.strip()
    except anthropic.APIError as e:
        logger.error("Call 4 (improved content) failed: %s", e)
        result.improved_markdown = (
            "# Error\n\nFailed to generate improved content. "
            "Please check your API key and try again."
        )

    # --- Call 5: Schema markup suggestions ---
    if verbose:
        logger.info("Generating schema markup suggestions...")

    prompt_5 = f"""\
Generate structured data markup suggestions for this blog post.

TITLE: {content.title}
AUTHOR: {content.author or '[AUTHOR NAME]'}
DATE: {content.publish_date or '[PUBLISH DATE]'}
URL: {content.url}
DESCRIPTION: {content.meta_description or result.quick_answer}

FAQ QUESTIONS:
{json.dumps(result.faq_questions[:5], indent=2)}

Respond with JSON containing these keys:
{{
  "article_schema": {{ ... complete Article JSON-LD schema ... }},
  "faq_schema": {{ ... complete FAQPage JSON-LD schema with the questions ... }}
}}

Use schema.org vocabulary. Include all required and recommended properties. \
Use placeholder values like [YOUR_IMAGE_URL] where needed.\
"""

    try:
        resp = _call_claude(client, prompt_5, max_tokens=3000)
        data = _parse_json_response(resp)
        result.schema_suggestions = data
    except (json.JSONDecodeError, anthropic.APIError) as e:
        logger.error("Call 5 (schema) failed: %s", e)

    return result
